### PR TITLE
First version

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by doudou** [comment]
@leifole here it is ... it's not completely tested (unit and real). So far, I get the configuration and the IMU-related data. I'm going to test the GPS stuff ASAP.

**Comment by leifole** [comment]
@doudou Nice. I think I can test it tomorrow morning with the Spatial Dual.

**Comment by doudou** [comment]
There's also the corresponding orogen component. I'm testing it right now with a Spatial Dual as well. There's a bunch of things that are not there because I used the Motus documentation and they removed the parts of the protocol that were specific to higher-end stuff. I'll probably add it today or tomorrow.

The binary tool (imu_advanced_navigation_anpp_ctl) only allows to query information. Right now, you need to use the component to actually read the data.

Also, the errors and how the position is reported are probably wrong. I've done it "gut feeling" and know it's wrong. I'm all for having some input here ;-) Thought I would look at how the other driver does it.

Finally, any comment on the shape of the API would be very welcome ;-) I probably over-engineered it, and would very much like to have a second and third look at it.

**Comment by leifole** [comment]
@doudou Still at it. Our IMU is mounted in one of those fancy Payload-Compartments, so I can only test it on the real system outdoors.

*whine on* And then the rain. And then no bootstrap with up-to-date base-types. And then battery failure. And then... *whine off*

**Comment by doudou** [comment]
Actually, to test the orogen stuff you would also have needed to get the C++11 patches from `base/cmake`. I just merged the orogen/typelib parts of C++11/14 support thanks to Malte.

I would suggest that you wait until that stuff is in master. Would make things easier for you.

**Comment by doudou** [comment]
At least, here, both component and driver work like a charm on a Motus and Spatial Dual. I couldn't get a dual-GNSS heading, but it seems to be related to the environment we're in (at least according to advanced navigation's support)

**Comment by leifole** [comment]
Compiled the comprehensive driver today on our system and tested the Main.cpp (imu_..._ctl) with the "info" command. Experienced timeouts after the the output of the first read call to the IMU (ser. no, etc., noting this down at home from my memory). Also after raising the timeout values, but that may very well be related to our serial-tcp converter. Will debug that tomorrow. 
Have you set anything different from the factory settings concerning which packets are outputted with the DualManager GUI?

Am 21. August 2017 18:03:10 MESZ schrieb Sylvain Joyeux <notifications@github.com>:
>At least, here, both component and driver work like a charm on a Motus
>and Spatial Dual. I couldn't get a dual-GNSS heading, but it seems to
>be related to the environment we're in (at least according to advanced
>navigation's support)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rock-drivers/drivers-imu_advanced_navigation_anpp/pull/1#issuecomment-323785196

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by doudou** [comment]
> Have you set anything different from the factory settings concerning which packets are outputted with the DualManager GUI?

My policy is to always leave the device configured from factory settings, and let the driver do the rest. Having manually perma-configured devices is the best way to kill reproduceability (what's the actual configuration ? It's not part of the logs)

The `_ctl` tool is limited in this respect (the only setting it allows to change is the baudrate). The orogen driver sets the message periods according to its configuration to have "complete" types (georeferenced RBS, accelerations, ...). See https://github.com/rock-drivers/drivers-orogen-imu_advanced_navigation_anpp/blob/first_version/tasks/Task.cpp#L45

For the timeout, it very well may be an issue with your chain. The default timeout is fairly low (1s). Could be set higher if that solves your problem, just tell me what's reasonable for your setup.

**Comment by doudou** [comment]
This worked reasonably well so far (apart from the alignment issue). I'm going to merge this as "beta version".

**Pull request merged**
